Name:           ros-hydro-pr2-sith
Version:        1.0.1
Release:        0%{?dist}
Summary:        ROS pr2_sith package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/pr2_sith
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-actionlib
Requires:       ros-hydro-dynamic-reconfigure
Requires:       ros-hydro-pr2-controllers-msgs
Requires:       ros-hydro-pr2-gripper-sensor-action
Requires:       ros-hydro-pr2-gripper-sensor-controller
Requires:       ros-hydro-pr2-gripper-sensor-msgs
Requires:       ros-hydro-pr2-precise-trajectory
Requires:       ros-hydro-rospy
Requires:       ros-hydro-sensor-msgs
BuildRequires:  ros-hydro-actionlib
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-dynamic-reconfigure
BuildRequires:  ros-hydro-pr2-controllers-msgs
BuildRequires:  ros-hydro-pr2-gripper-sensor-action
BuildRequires:  ros-hydro-pr2-gripper-sensor-controller
BuildRequires:  ros-hydro-pr2-gripper-sensor-msgs
BuildRequires:  ros-hydro-pr2-precise-trajectory
BuildRequires:  ros-hydro-rospy
BuildRequires:  ros-hydro-sensor-msgs

%description
An extension of the PR2 props demo, but instead of high fives, the PR2 swings a
lightsaber until it detects an impact.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Tue Sep 16 2014 Devon Ash <dash@clearpathrobotics.com> - 1.0.1-0
- Autogenerated by Bloom

